const BACKEND = "https://skilful-earth-388409.as.r.appspot.com/backend/";
const BACKEND_LOGIN = BACKEND + "verify";
const BACKEND_GET_WORD_LIST = BACKEND + "getWords";
const BACKEND_GET_ALLOWED_WORD_LIST = BACKEND + "getAllowedWords";
const BACKEND_ADD_WORD = BACKEND + "addWord";
const BACKEND_ADD_ALLOWED_WORD = BACKEND + "addAllowedWord";
const BACKEND_REMOVE_WORD = BACKEND + "deleteWord";
const BACKEND_REMOVE_ALLOWED_WORD = BACKEND + "deleteAllowedWord";

export { BACKEND_LOGIN, BACKEND_GET_WORD_LIST, BACKEND_GET_ALLOWED_WORD_LIST, BACKEND_ADD_WORD,
    BACKEND_ADD_ALLOWED_WORD, BACKEND_REMOVE_WORD, BACKEND_REMOVE_ALLOWED_WORD };